[feature/deposit]: creating deposit feature
igordantasgf/MATA88-Sistemas_Distribuidos pull request #4
Opened 2023-11-28 01:54 UTC by alexandrefscampos

2023-11-28 01:58 UTC, igordantasgf commented on banco.py
Please create **Banco** class to have those functions

2023-11-28 01:59 UTC, igordantasgf requested changes

2023-11-28 01:59 UTC, igordantasgf commented on banco.py
Please create Banco class to have those functions

2023-11-29 00:06 UTC, igordantasgf approved these changes

2023-11-29 00:11 UTC, Beckhauser1 commented
Please, resolve the conflict

2023-11-29 00:12 UTC, merged